#Your build pipeline references an undefined variable named ‘Parameters.mavenPOMFile’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘Parameters.sqAnalysisEnabled’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘Parameters.sqMavenPluginVersionChoice’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

#Your build pipeline references an undefined variable named ‘Parameters.checkstyleAnalysisEnabled’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972



steps:

- task: Maven@3

  displayName: 'Maven pom.xml'

  inputs:

    mavenPomFile: '$(Parameters.mavenPOMFile)'

    sonarQubeRunAnalysis: '$(Parameters.sqAnalysisEnabled)'

    sqMavenPluginVersionChoice: '$(Parameters.sqMavenPluginVersionChoice)'

    checkStyleRunAnalysis: '$(Parameters.checkstyleAnalysisEnabled)'

    pmdRunAnalysis: true

    findBugsRunAnalysis: true
